
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:$apr1$LrZ7NOjP$/jqzap/h/XTN4YNMejd311"]


[entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]


[api]
entrypoint="dashboard"

[acme]
email = "correo" ----------------Especificar correo
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"


[docker]
domain = "fisc.online"
watch = true
network = "web"
